language: php
sudo: false
services: redis-server
install:
  - pecl install redis
before_script:
  - composer install --no-interaction --prefer-source --dev
script:
  - vendor/bin/phpunit -c phpunit.xml.travisci
matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
      dist: trusty
